### ISSUE TITLE
Unable to install spp_1.14.tar.gz - boost version minimum?

### ISSUE THREAD

**Issue by jjv5** [kundajelab/phantompeakqualtools#15]
Installation of spp R package gives many errors:

bed2vector.cpp: In function 'SEXPREC* read_bed_ends(SEXP)':
bed2vector.cpp:118:55: error: template argument 3 is invalid
   hash_map<string, int, hash<string>,equal_to<string> > cind_map;
                                                       ^
bed2vector.cpp:163:59: error: template argument 3 is invalid
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                           ^
bed2vector.cpp:163:77: error: qualified-id in declaration before 'li'
       hash_map<string, int, hash<string>,equal_to<string> >::const_iterator li=cind_map.find(chr);
                                                                             ^~
bed2vector.cpp:165:10: error: 'li' was not declared in this scope
       if(li==cind_map.end()) {
          ^~
bed2vector.cpp:165:23: error: request for member 'end' in 'cind_map', which is of non-class type 'int'
       if(li==cind_map.end()) {
                       ^~~
bed2vector.cpp:169:10: error: no match for 'operator[]' (operand types are 'int' and 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}')
  cind_map[chr]=cind;

Is this perhaps related to wrong boost version? What version of boost libs is needed?

CentOS 6
R version 3.5.1
boost                     1.69.0          py37h8619c78_1001    conda-forge
boost-cpp                 1.69.0            h11c811c_1000    conda-forge

**Comment by leepc12** [comment]
We use Ubuntu's docker image `ubuntu:18.04` and `apt-get install libboost-dev` for boost. It's `1.65`. But our chip-seq pipeline's docker image use higher version of R and R packages (e.g. spp==1.16).

We recommend to install our chip-seq-pipeline's Conda environment since it already has R and R packages (lower version of spp==1.13) required for `run_spp.R` and it also has `run_spp.R` itself.

https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/docs/install_conda.md

**Comment by lufuhao** [comment]
Tested https://cran.r-project.org/src/contrib/Archive/spp/spp_1.16.0.tar.gz
fully working on ubuntu 22.04

**Comment by lufuhao** [comment]
spp 1.16 full working on ubuntu 22.04.
